config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<div>
  <h1>All our Flats(<%= @flats.count %>)</h1>
</div>
<div class="row">
    <% @flats.each do |flat| %>
      <div class="col-4">
        <div class="flat-card">
          <div class="flat-card-content">
            <div class="flat-card-title">
              <h4><%= flat.name %></h4>
            </div>
            <p><i class="fa-solid fa-location-dot"></i> <%= flat.address %></p>
            <div class="flex">
              <div class="flex">
                <span><%= flat.number_of_guests %></span> <i class="fa-solid fa-user"></i>
              </div>
              <div class="flex ml-3">
                <i class="fa-solid fa-euro-sign"></i> <%= flat.price_per_night %>
              </div>
            </div>
          </div>
          <div class="flat-card-actions">
            <%= link_to 'More info', flat_path(flat) %>
            <a href="#" class="ml-3 text-warning">Edit</a>
            <a href="#" class="ml-3 text-danger">Remove</a>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
  <nav class="navbar navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand">Simple Airbnb</a>
    <form class="d-flex">
      <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success" type="submit">Search</button>
      <a class="btn btn-outline-primary my-2 my-sm-0 ms-2" href="/flats/new">Add Flat</a>
    </form>
  </div>
    <%= yield %>
  </body>
</html>